# Generated by Django 2.2.5 on 2019-09-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_auto_20190905_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='dt_criacao',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(choices=[('Único', 'Único'), ('Mensal', 'Mensal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='forma_pagamento',
            name='nome',
            field=models.CharField(choices=[('Crédito', 'Crédito'), ('Débito', 'Débito'), ('Dinheiro', 'Dinheiro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tipo_transacao',
            name='nome',
            field=models.CharField(choices=[('Recebimento', 'Recebimento'), ('Pagamento', 'Pagamento')], max_length=100),
        ),
    ]
