# Generated by Django 2.2.5 on 2019-09-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_auto_20190906_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='forma_pagamento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipo_transacao',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
