# Generated by Django 2.2.5 on 2019-09-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_auto_20190906_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='dt_transacao',
            field=models.DateField(),
        ),
    ]
